server:
  port: 10001

spring:
  application: 
    name: demo-springcloud2-consumer
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instanceId: ${spring.application.name}:${spring.application.instance_id:${spring.cloud.client.ip-address}:${server.port}}  