server:
  port: 16001
  servlet:
    context-path: /auth # 应用名 localhost:8090/auth


spring:
  redis:
    database: 0
    host: 192.168.1.117
    port: 6381
#    password:
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
  # 数据源配置
  datasource:
    username: root
    password: 1qa@WS
    url: jdbc:mysql://127.0.0.1:3306/demo-springcloud-oauth?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
    #mysql8版本以上驱动包指定新的驱动类
    driver-class-name: com.mysql.cj.jdbc.Driver
    #   数据源其他配置, 在 DruidConfig配置类中手动绑定
    initialSize: 8
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL