server:
  port: 10011

spring:
  application:
    name: demo-springcloud-2-oauth-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.118:3306/demo-springcloud-oauth?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 1qa@WS
    # 数据源其他配置, 在 DruidConfig配置类中手动绑定
    initialSize: 8
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL

management:
  security:
    enabled: false # 关闭验证
  endpoints: # 开放监控端口
    web:
      exposure:
        include: "*"
      
logging:
  level:
    root: info
    com.cloud: debug
  file: logs/${spring.application.name}.log    
      