server:
  port: 15001

spring:
  application:
    name: demo-springcloud-2-provider-user
  cloud:
    stream:
      default:
        consumer:
          maxAttempts: 5
          backOffInitialInterval: 2000
          backOffMultiplier: 5
          backOffMaxInterval: 1500000
      bindings:
        myinput:
          destination: my-exchange
          group: my-input-group
          contentType: application/json
          
hystrix:
  command:
    default:
      execution:
        isolation:
          thread: 
           timeoutInMilliseconds: 1000 # 服务调用超时时长 

management:
  security:
    enabled: false # 关闭验证
  endpoints: # 开放监控端口
    web:
      exposure:
        include: "*"
    