server:
  port: 16001

spring:
  application:
    name: demo-springcloud-2-service-order
  cloud:
    stream:
      default:
        consumer:
          maxAttempts: 5
          backOffInitialInterval: 2000
          backOffMultiplier: 5
          backOffMaxInterval: 1500000
      bindings:
        myoutput:
          destination: my-exchange
          group: my-output-group
          contentType: application/json
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.118:3306/demo-springcloud-provider-order?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 1qa@WS
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    open-in-view: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true

management:
  security:
    enabled: false # 关闭验证
  endpoints: # 开放监控端口
    web:
      exposure:
        include: "*"