server:
  port: 10031

spring:
  application:
    name: demo-springcloud-2-service-user
  cloud:
    stream:
      default:
        consumer:
          maxAttempts: 5
          backOffInitialInterval: 2000
          backOffMultiplier: 5
          backOffMaxInterval: 1500000
      bindings:
        myinput:
          destination: my-exchange
          group: my-input-group
          contentType: application/json
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.118:3306/demo-springcloud-service-user?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 1qa@WS
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    open-in-view: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true

ribbon: # 在Feign中Ribbon的配置
  ConnectionTimeout: 1000 # Feign 连接超时配置，默认1000
  ReadTimeOut: 1000 # 读取超时，默认1000

# Feign中使用Hystrix配置
feign:
  hystrix:
    enabled: true # 在Feign中Hystrix的开关

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
           timeoutInMilliseconds: 2000 # 服务调用超时时长
      circuitBreaker: # 断路器
        enabled: true # 是否开启断路器，默认true
        requestVolumeThreshold: 3 # 断路器阈值，默认20
        sleepWindowInMilliseconds: 30000 # 休眠时间窗，默认值5000(5秒)
        errorThresholdPercentage: 60 # 超时/失败百分比，默认50（50%）

logging:
  level:
    root: info
    com.cloud: debug
  file: logs/${spring.application.name}.log

management:
  security:
    enabled: false # 关闭验证
  endpoints: # 开放监控端口
    web:
      exposure:
        include: "*"
        
swagger:
  title: 用户管理
  version: 1.0
  description: 用户管理接口文档
  basePackage: com.alisls.demo.springcloud.service.user.web