server:
  port: 8761

eureka:
  instance:
    hostname: localhost # 实例
  client:
    register-with-eureka: false # 是否注册到eureka
    fetch-registry: false # 检索服务
  service-url:
    defaultZone: http://localhost:8761/eureka # 在哪个地址查找eureka实例
  server:
    wait-time-in-ms-when-sync-empty: 0  # 当 eureka启动时，不能从集群获取，应该等多久
    enable-self-preservation: false # 自我保护是否开启
    eviction-interval-timer-in-ms: 60000 # 服务失效剔除时长，默认60秒
    peer-eureka-nodes-update-interval-ms: 10000 # 获取数据间隔

spring:
  application:
    name: demo-springcloud-2-eureka
  security:
    user:
      name: root
      password: root